### ISSUE TITLE
Backend at capacity

### ISSUE THREAD

**Issue by amamut** [pebble-examples/hello-timeline#2]
Getting this message running the app:

```
Error getting timeline token: 503 Server Error: Service Unavailable: Back-end server is at capacity
```

I have been getting this error since around 8am EST. Is this something to do with the pebble back-end or my back-end?

**Comment by matthewtole** [comment]
We experienced some downtime with some of our servers earlier today, which caused the error that you encountered. The issue has been resolved, so if you try again it should be working now.
